---
title: "ESJ Map"
author: "Brian"
date: "2/14/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(cluster)
library(viridis)
library(leaflet)
library(mapview)
library(tmap)
library(sf)
```

```{r}
read_rds("kc_demographics.rds")
glimpse(kc_demographics, width = 100)
```


```{r}
set.seed(23994)
vars <- c('med_income', 'p_e_less', 'percent_poc')#variables needed
equity_matrix <- cluster::daisy(kc_demographics[,vars])
res.pam <- cluster::pam(x=equity_matrix,k = 5,cluster.only = F)
#test
kc_demographics$cluster <- as.double(res.pam$clustering)
#kc_demographics$cluster <- as.factor(res.pam$clustering)
#kc_demographics$cluster=factor(dataCSV$cluster,
#                           levels=c(1,3,2),
#                           labels=c("low","mid","best"), 
#                           ordered=T)
```

Exploring the data

```{r}
kc_demographics %>% glimpse()
table(kc_demographics$cluster,
                exclude = 'nothing')
summary(kc_demographics$cluster)
summary_income <- aggregate(data=kc_demographics, med_income~cluster, median)
summary_english <- aggregate(data=kc_demographics, p_e_less~cluster, mean)
summary_poc <- aggregate(data=kc_demographics, percent_poc~cluster, mean)
esj_summary <- summary_income %>% inner_join(summary_english) %>% inner_join(summary_poc)
esj_summary[order(esj_summary$percent_poc),]
```

```{r}
kc_demographics$cluster <- factor(kc_demographics$cluster,
                                  levels=c(1,5,2,3,4),
                                  labels=c("low income diverse",
                                           "low income middle diverse",
                                           "middle income middle diverse", 
                                           "high income low diversity", 
                                           "middle income low diversity"),
                                  ordered=T)
kc_demographics
```

```{r}
ESJ_map <- kc_demographics %>% mutate(esj_score = as.integer(cluster)) %>%
  st_sf() %>%
  ggplot(
    aes(fill = esj_score)) +
  geom_sf() +
  scale_fill_viridis()
ESJ_map
```

```{r}
kc_demographics %>% st_sf() %>% mapview(zcol = "cluster")
```

try to replicate [this awesome map with a graph in it](https://walker-data.com/census-r/mapping-census-data-with-r.html)
```{r}
#tm_shape(hennepin_black, 
#         projection = sf::st_crs(26915)) + 
#  tm_polygons(col = "percent",
#          style = "jenks",
#          n = 5,
#          palette = "Purples",
#          title = "ACS estimate",
#          legend.hist = TRUE) + 
#  tm_layout(title = "Percent Black\nby Census tract",
#            frame = FALSE,
#            legend.outside = TRUE,
#            bg.color = "grey70",
#            legend.hist.width = 5,
#            fontfamily = "Verdana")
```

